### horizontal pod autoscaling.

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  name: skate-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: skate-ingress
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource: 
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70    