apiVersion: batch/v1
kind: CronJob
metadata:
  name: temp-cron
spec:
  schedule: "* * * * *"
  jobTemplate:
    metadata:
      labels: 
        app: web
    spec:
      template:
        metadata:
          labels:
            app: web
        spec:
          containers:
            - name: tx-cron
              image: alpine
              args:
                - sleep
                - 30s
          restartPolicy: OnFailure                     