apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-deploy
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      colour: pink
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        colour: pink
    spec: 
      containers:
        - name: books-pod
          image: shaikkhajaibrahim/libbookssvc:1.0
          envFrom:
            - secretRef:
                name: booksservice-secrets
          ports:
            - containerPort: 8000
          resources:  
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service   
metadata: 
  name: bookservice-deploy
spec:
  type: ClusterIP
  selector: 
    colour: pink
  ports:
    - port: 8000
      targetPort: 8000                             