apiVersion: v1
kind: Pod
metadata:
  name: sadik
spec:
  containers:
    - name: mysql-container
      image: mysql:9
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: library
        - name: MYSQL_USER
          value: sadik
        - name: MYSQL_PASSWORD
          value: sadik
      resources:
        requests: 
          memory: 128M
          cpu: 250m
        limits:
          memory: 500M
          cpu: 1000m
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: mysqlvol
          mountPath: /var/lib/mysql
  volumes:
    - name: mysqlvol
      persistentVolumeClaim:
        claimName: mysql-pvc
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
