apiVersion: v1
kind: ConfigMap
metadata: 
  name: config-books-db
data:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_DB: booksdb
---

apiVersion: v1
kind: ConfigMap
metadata: 
  name: config-books-service
data:
  DATABASE_URL: postgresql://user:password@booksdb-sts-0.booksdb-service:5432/booksdb
  SECRET_KEY: YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k

---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: config-users-db
data:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_DB: usersdb 
---  
apiVersion: v1
kind: ConfigMap
metadata: 
  name: config-users-service
data:
  DATABASE_URL: postgresql://user:password@usersdb-sts-0.usersdb-service:5432/usersdb
  SECRET_KEY: YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k