apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: king-deamon
  labels:
    app: google
spec: 
  minReadySeconds: 5
  selector: 
    matchLabels:
      colour: white
  template: 
    metadata:
      labels:
        colour: white
    spec: 
      containers:
        - name: james
          image: fluent/fluentd:edge-debian
          resources:
            requests:
              cpu: 200m
              memory: 64M
            limits:
              cpu: 300m
              memory: 128M
          ports:
            - containerPort: 9880
              name: fluentd