  apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    name: books-src-rep
    labels:
      app: rapido
  spec:
    minReadySeconds: 5
    replicas: 1
    selector:
      matchLabels:
        colour: violet
    template:
      metadata: 
        labels:
          colour: violet
      spec: 
        containers:
          - name: books-pod
            image: shaikkhajaibrahim/libbookssvc:1.0
            envFrom:
              - configMapRef:
                  name: config-books-service
              - secretRef:
                  name: booksservice-secrets
            ports:
              - containerPort: 8000
            resources:
              requests:
                memory: 24M
                cpu: 100m
              limits:
                memory: 128M
                cpu: 500m


---

apiVersion: v1
kind: Service
metadata:
  name: books-service-src
spec:
  type: NodePort
  selector:
    colour: violet
  ports:
    - port: 8000
      targetPort: 8000  


                        

