apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: books-db-rep
  labels:
    app: browny
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      colour: yellow
  template:
    metadata: 
      labels:
        colour: yellow
    spec: 
      containers:
        - name: book-db-pod
          image: postgres:15-alpine
          envFrom:
            - configMapRef: 
                name: config-books-db
            - secretRef:
                name: booksdb-secrets
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: 24M
              cpu: 100m
            limits:
              memory: 128M
              cpu: 500m


---

apiVersion: v1
kind: Service
metadata:
  name: books-db-src
spec:
  type: ClusterIP
  selector:
    colour: yellow
  ports:
    - port: 5432
      targetPort: 5432  


                       
